name: Sync Roadmap to GitHub Projects

on:
  push:
    paths:
      - 'constants/roadmap.ts'
      - 'docs/ROADMAP_Q1_Q2_2025.md'
  workflow_dispatch:

jobs:
  sync-roadmap:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Extract roadmap items
        id: extract
        run: |
          echo "Roadmap sync triggered - manual issue creation recommended"
          echo "See docs/GITHUB_PROJECTS_SETUP.md for instructions"

      - name: Comment on commit
        uses: actions/github-script@v7
        with:
          script: |
            const message = `
            🗺️ **Roadmap Updated**

            The roadmap has been updated. Please review and sync with GitHub Projects:

            1. Visit [Projects](https://github.com/${{ github.repository }}/projects)
            2. Review changes in \`constants/roadmap.ts\`
            3. Create/update issues as needed
            4. See \`docs/GITHUB_PROJECTS_SETUP.md\` for details

            **Quick links**:
            - [Roadmap Q1-Q2 2025](/docs/ROADMAP_Q1_Q2_2025.md)
            - [Issue Template](/.github/ISSUE_TEMPLATE/roadmap-feature.md)
            `;

            // Find the commit SHA
            const sha = context.sha;

            console.log('Roadmap sync notification created');
            console.log(message);
